development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://redis:6379/1" } %>

test:
  adapter: test

production:
  adapter: redis
  url: redis://192.168.99.100:6379
  channel_prefix: hourly_production
